# Generated by Django 4.1 on 2022-08-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookinfo.category'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='isbn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='num_of_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='press',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='translator',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='type_of_lang',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='book_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookinfo.bookinfo'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.DeleteModel(
            name='BookDetail',
        ),
    ]
